### PR TITLE
Add support for matching tags using regular expressions

### PR DESCRIPTION
**Pull request by esb**

### CODE REVIEW

**Comment by skatkov** [comment]
You changes has caused test to fail. I would appreciate if you could fix them.

Can you please provide a bit more information about the change? Do you have a use case for it? I was considering similar functionality, but couldn't find a usecase that would justify it.

**Comment by skatkov** [comment]
Oh, noticed that you already explained your use case in #11 issue. If you will get testsuit to green, I'd be happy to release it.

**Comment by cattekin** [comment]
@skatkov this PR would probably pass checks if it was rebased off master

**Comment by skatkov** [comment]
@cattekin 

Thanks for nudging. I've noticed that author of this pull request actually provided an valid use case for this code.

I'll try to come back to this PR later. If anyone is keen to rebase this (or create a separate PR) -- i'll be happy to merge.

**Comment by skatkov** [comment]
Closing due to lack of activity

**Pull request closed without merging**
