### PR TITLE
enable integer type

### PR DESCRIPTION
**Pull request by devvit**
follow @skatkov to add integer type support, yes, I need a integer solution :)

### CODE REVIEW

**Comment by skatkov** [comment]
@devvit would be great if you can increment version number as well ;-)

**Comment by skatkov** [comment]
It would probably be great to leave a note in README as well about this -- there wasn't much sense in doing that with my changes. By with integer support, we probably need to note that multiple array types are supported.

**Comment by devvit** [comment]
sure, @skatkov

**Comment by tmiyamon** [comment]
Nice work! thanks guys!

**Pull request merged**
