### PR TITLE
Features/rails5 ready

### PR DESCRIPTION
**Pull request by bunnymatic**
* Update the calls for `all_<tags>` so the work with Rails 5 ActiveRecord calls.

Rails 5 seemed to be returning arrays from the `.uniq` calls so moving to a postgres `distinct` kept that return as a relation.

Cheers

### CODE REVIEW

**Comment by auscaster** [comment]
It would be great to get this merged in, I imagine there are many people using Rails 5 that want to use this.

**Comment by auscaster** [comment]
Looks like the CI ruby version needs to be updated to get tests passing.

**Comment by bunnymatic** [comment]
I was just about to put this PR in a more permanent branch and noticed the latest master (version 0.4.0) has changes that may fix this for rails 5.  This may not need to be merged in as it may have been solved by d21cdd71bc54895c30f350ebd37da9afbdd9645d.  

For rails5 support, you might try that version and see if it works.

**Comment by auscaster** [comment]
Thanks, I noticed that myself and can confirm its working :)

**Comment by bunnymatic** [comment]
As noted above, someone else's merge has solved the rails 5 issues.

Closing

**Pull request closed without merging**
