### PR TITLE
Add support for UUID arrays

### PR DESCRIPTION
**Pull request by eneagoe**
This adds support for UUID arrays, very similar to https://github.com/tmiyamon/acts-as-taggable-array-on/pull/43

### CODE REVIEW

**Comment by skatkov** [comment]
It would be great if you can update README.md as well. So far, citext or uuid support is not really publicly known. :)

**Comment by eneagoe** [comment]
I've updated the PR - sorry for missing the docs and the correct changelog format. Thank you!

**Review by skatkov — APPROVED** [review]

**Comment by skatkov** [comment]
@eneagoe thanks for your contribution. 

I don't really use this library anymore, would be great to give you maintainer access, but I don't have rights to do so.

**Comment by eneagoe** [comment]
Thank you for the time & quick feedback!

**Pull request merged**
